### ISSUE TITLE
Prettier check fails in Github Actions

### ISSUE THREAD

**Issue by Yamaguchi** [chaintope/tapyrusrb#34]
https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33

```
Run bundle exec rbprettier --check .
[warn] lib/tapyrus.rb
Error:  lib/tapyrus/script/script_error.rb: Error: nesting of 100 is too deep
Error:      at parseSync (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/dist/parser/parseSync.js:171:23)
Error:      at Object.parse (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/dist/ruby/parser.js:13:[4](https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33#step:5:5)0)
Error:      at Object.parse$a [as parse] (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:12[5](https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33#step:5:6)13:19)
Error:      at coreFormat (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:14044:1[6](https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33#step:5:7))
Error:      at formatWithCursor$1 (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:14284:14)
Error:      at Object.formatWithCursor (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:59304:12)
Error:      at format$1 (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:16953:21)
Error:      at Object.formatFiles$1 [as formatFiles] (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:17067:16)
Error:      at async main (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:18925:5)
Error:      at async Object.run (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:18868:5)
Error:  lib/tapyrus/script/script_interpreter.rb: Error: nesting of 100 is too deep
Error:      at parseSync (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/dist/parser/parseSync.js:171:23)
Error:      at Object.parse (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/dist/ruby/parser.js:13:40)
Error:      at Object.parse$a [as parse] (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:12513:19)
Error:      at coreFormat (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:14044:16)
Error:      at formatWithCursor$1 (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:14284:14)
Error:      at Object.formatWithCursor (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/index.js:59304:12)
Error:      at format$1 (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:16953:21)
Error:      at Object.formatFiles$1 [as formatFiles] (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:1[7](https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33#step:5:8)067:16)
Error:      at async main (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:1[8](https://github.com/chaintope/tapyrusrb/actions/runs/7110333535/job/19356665302?pr=33#step:5:9)925:5)
Error:      at async Object.run (/home/runner/work/tapyrusrb/tapyrusrb/vendor/bundle/ruby/3.0.0/gems/prettier-2.0.0/node_modules/prettier/bin-prettier.js:18868:5)
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Checking formatting...
Error: Process completed with exit code 2.
```

**Comment by Yamaguchi** [comment]
json_pureの依存をinstallしたときに、2.7.1以上だとエラーになるようですので、とりあえず2.6.3で固定しておきます。
(https://github.com/chaintope/tapyrusrb/pull/32)
